channel:
  description: set a channel(s) value
  fields:
    name:
      description: The name of the universe
      example: dmx1
    channel:
      description: the index(s) of the channel. 10, [10,20], [10,20,3] -> will jump 3
      example: 10
    value:
      description: the value(s) to set the channel to. 50, [0,100], [100,0]
      example: 50

universe:
  description: set a universe parameters
  fields:
    name:
      description: The name of the universe
      example: dmx1
    universe:
      description: the port index. a value [0-255]
      example: 1
    subnet:
      description: the net/subnet value [0-255]
      example: 10
    fps:
      description: the frame per second to send artnet. 0 means only on change
      example: 25

fade:
  description: fade any entity with any service
  fields:
    entity_id:
      description: The entity id or [entity1, entity2, entity3]
      example: light.kitchen_main_lamp
    range:
      description: while entity_id is part of the name, use range to add mutiple entites. Example entity_id=rgb_ and range=[1,4] will be [rgb_1,rgb_2,rgb_3,rgb_4]
    service:
      description: the service to call to
      example: light.turn_on
    transition:
      description: the fade time in seconds
      example: 2.5
    offset:
      description: the spread of time in seconds must be lower than transition
    start:
      description: Optional. The attrbiutes and values to start from. This value is not must, system will take the current entity values
    end:
      description:  The attrbiutes and values to goto.
      example: "{brightness: 255, hs_color: [300,100]}"
    ease:
      description: Optional. The fade method to control Linear, Quad, Cubic, Quart, Quint, Sine, Expo, Circ, Elastic, Back, Bounce, each one have In, Out and InOut
    delay:
      description: Optional. The delay time before animation starts, by default it is 0
    loop:
      description: Optional. how many loops to repeat. default is 1, 0 is endless loop
    loopDelay:
      description: Optional. The time to wait before you start a new loop. default is 0


patch:
  description: will load the config/lights/conx.yaml and add the new patch to its dmx part
  fields:
    dmxName:
      description: the dmx
      example: dmx1

    channel:
      description: the starting channel to start the entire patch from
      example: 1

    name:
      description: The name initial name of all the light entities
      example: rgb_

    start:
      description: the starting number for the name
      example: 1

    type:
      description: The type of the light [dimmer,rgb,rgba]
      example: rgb

    count:
      description: The number of entites to create
      example: 10


automata_send:
  description: send packet to automata box
  fields:
    name:
      description: The name of the automata box
      example: auto1
    data:
      description: data to send
      example: "[1=ON]"

kincony_send:
  description: send packet to kincony box
  fields:
    name:
      description: The name of the kincony box
      example: auto1
    data:
      description: data to send
      example: "RELAY-GET_INPUT-255"

