restore:
  description: restore the initial state of this entitiy_id (just before last system shutdown)
  fields:
    id:
      description: The entity id
      example: light.kitchen_main_lamp
    attr:
      description: if no attr is define return the state else return the attribute of the state
      example: humidity

save:
  description: save a state to database
  fields:
    id:
      description: The entity id
      example: light.kitchen_main_lamp
    state:
      description: the value to save
      example: 5000

channel:
  description: set a channel(s) value
  fields:
    name:
      description: The name of the universe
      example: dmx1
    channel:
      description: the index(s) of the channel. 10, [10,20], [10,20,3] -> will jump 3
      example: 10
    value:
      description: the value(s) to set the channel to. 50, [0,100], [100,0]
      example: 50