- platform: conx
  automata:
  - boxName: autoBox2
    channel: 1
    name: conxAutoLight1

  - boxName: autoBox2
    channel: 2
    name: conxAutoLight2

  - boxName: autoBox2
    channel: 3
    name: conxAutoLight3

  auto4color:
  - name: fuckingAuto
    ip: 192.168.1.36
    port: 1005

