- platform: conx
  dmx:
  - dmxName: dmx1
    channel: 1
    name: dim_;1>100
    fixture: dim
    fadeOn: 4
    fadeOff: 2
    type: dimmer

  - dmxName: dmx1
    channel: 101
    name: rgb_;1>10
    fixture: rgb
    fadeOn: 4
    fadeOff: 2
    type: rgb


