- platform: conx
  dmx:
  - dmxName: dmx1
    channel: 1
    name: dim_;1>10
    fadeOn: 4
    fadeOff: 2
    type: dimmer

  - dmxName: dmx1
    channel: 11
    name: rgb_;1>10
    fadeOn: 4
    fadeOff: 2
    type: rgb



