- platform: conx
  dmx:

#PAR_LED_1
    - dmxName: dmx4
      channel: 1
      name: par_dimmer_001
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 2
      name: par_rgb_001
      type: rgb

    - dmxName: dmx4
      channel: 5
      name: par_amber_001
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 6
      name: par_white_001
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 7
      name: par_strob_001
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_2
    - dmxName: dmx4
      channel: 8
      name: par_dimmer_002
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 9
      name: par_rgb_002
      type: rgb

    - dmxName: dmx4
      channel: 12
      name: par_amber_002
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 13
      name: par_white_002
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 14
      name: par_strob_002
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_3
    - dmxName: dmx4
      channel: 15
      name: par_dimmer_003
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 16
      name: par_rgb_003
      type: rgb

    - dmxName: dmx4
      channel: 19
      name: par_amber_003
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 20
      name: par_white_003
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 21
      name: par_strob_003
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_4
    - dmxName: dmx4
      channel: 22
      name: par_dimmer_004
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 23
      name: par_rgb_004
      type: rgb

    - dmxName: dmx4
      channel: 26
      name: par_amber_004
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 27
      name: par_white_004
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 28
      name: par_strob_004
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_5
    - dmxName: dmx4
      channel: 29
      name: par_dimmer_005
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 30
      name: par_rgb_005
      type: rgb

    - dmxName: dmx4
      channel: 33
      name: par_amber_005
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 34
      name: par_white_005
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 35
      name: par_strob_005
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_6
    - dmxName: dmx4
      channel: 36
      name: par_dimmer_006
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 37
      name: par_rgb_006
      type: rgb

    - dmxName: dmx4
      channel: 40
      name: par_amber_006
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 41
      name: par_white_006
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 42
      name: par_strob_006
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_7
    - dmxName: dmx4
      channel: 43
      name: par_dimmer_007
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 44
      name: par_rgb_007
      type: rgb

    - dmxName: dmx4
      channel: 47
      name: par_amber_007
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 48
      name: par_white_007
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 49
      name: par_strob_007
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_8
    - dmxName: dmx4
      channel: 50
      name: par_dimmer_008
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 51
      name: par_rgb_008
      type: rgb

    - dmxName: dmx4
      channel: 54
      name: par_amber_008
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 55
      name: par_white_008
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 56
      name: par_strob_008
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_9
    - dmxName: dmx4
      channel: 57
      name: par_dimmer_000
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 58
      name: par_rgb_000
      type: rgb

    - dmxName: dmx4
      channel: 61
      name: par_amber_000
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 62
      name: par_white_000
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 63
      name: par_strob_000
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#PAR_LED_10
    - dmxName: dmx4
      channel: 64
      name: par_dimmer_010
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 65
      name: par_rgb_010
      type: rgb

    - dmxName: dmx4
      channel: 68
      name: par_amber_010
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 69
      name: par_white_010
      fadeOn: 2
      fadeOff: 2
      type: dimmer

    - dmxName: dmx4
      channel: 70
      name: par_strob_010
      fadeOn: 2
      fadeOff: 2
      type: dimmer

#RELAY_ON_OFF
    - dmxName: dmx4
      channel: 101
      name: relay_ner_1+9_001  #ner_1+9+baner
      type: dimmer

    - dmxName: dmx4
      channel: 102
      name: relay_ner_002  #ner_2
      type: dimmer

    - dmxName: dmx4
      channel: 103
      name: relay_ner_003  #ner_3
      type: dimmer

    - dmxName: dmx4
      channel: 104
      name: relay_ner_004  #ner_4
      type: dimmer

    - dmxName: dmx4
      channel: 105
      name: relay_ner_005  #ner_5
      type: dimmer

    - dmxName: dmx4
      channel: 106
      name: relay_ner_006  #ner_6
      type: dimmer

    - dmxName: dmx4
      channel: 107
      name: relay_ner_007  #ner_7
      type: dimmer

    - dmxName: dmx4
      channel: 108
      name: relay_ner_008  #ner_8
      type: dimmer
