- platform: conx
  kincony:
  - boxName: kinconyBox1
    channel: 1
    name: kinconyLight1

  - boxName: kinconyBox1
    channel: 2
    name: kinconyLight2

  - boxName: kinconyBox1
    channel: 3
    name: kinconyLight3
