- platform: conx
  automata:
    - boxName: autoBox1
      channel: 11
      name: conxSensor1

    - boxName: autoBox1
      channel: 12
      name: conxSensor2

    - boxName: autoBox1
      channel: 13
      name: conxSensor3

