- id: '1610039818897'
  alias: Selection
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.selection
  condition: []
  action:
  - service: conx.select
    data:
      id: '{{ states.input_text.selection.state }}

        '
  mode: single
- id: '1610122315991'
  alias: Name
  description: ''
  trigger:
  - platform: state
    entity_id: input_text.name
  condition: []
  action:
  - service: conx.name
    data:
      name: '{{ states.input_text.name.state }}

        '
  mode: single
- id: '1610124444994'
  alias: Transition
  description: ''
  trigger:
  - platform: state
    entity_id: input_number.transition
  condition: []
  action:
  - service: conx.transition
    data:
      value: '{{ states.input_number.transition.state }}

        '
  mode: single
