# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

media_player:

discovery:


# Text to speech
# Example configuration.yaml entry for Google Translate TTS service
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://127.0.0.1:8123
    service_name: google_say

conx:
  dmx:
    - name: "dmx1"
      ip: "192.168.1.25"
      universe: 1
      channels: 32
      level: 255
      fps: 30

    - name: "dmx2"
      universe: 2
      channels: 256

    - name: "dmx13"
      universe: 13

    - name: "dmx4"
      universe: 4



group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml

light:
  - platform: dmx
    host: 192.168.1.25 #House DMX Controller (eDMX King)
    port: 6454
    dmx_channels: 512
    default_level: 0
    universe: 0
    devices:
      #לדים ארון מטבח
      - channel: 1
        transition: 2
        name: mitbah
        type: dimmer
#logger:
#  default: info
#  logs:
#    custom_components.conx: debug
sensor:
  - platform: sql
    queries:
      - name: Sun state
        query: "SELECT * FROM states WHERE entity_id = 'sun.sun' ORDER BY state_id DESC LIMIT 1;"
        column: 'state'