# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#config:
#frontend:
#image:
#person:
#map:
#history:
#logbook:
#sun:


# Example filter to include specified domains and exclude specified entities
recorder:
  purge_keep_days: 1
  include:
    domains:
      - switch

history:
  use_include_order: true
  include:
    domains:
      - switch


# Text to speech
# Example configuration.yaml entry for Google Translate TTS service



group: !include groups.yaml
automation: !include_dir_list automation/
automation old: !include automations.yaml
#automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

conx: !include conx/devices.yaml
switch automata: !include conx/switches/automata.yaml
light dmx: !include conx/lights/dmx.yaml
#switch kincony: !include conx/switches/kincony.yaml
#sensor automata: !include conx/sensors/automata.yaml
#sensor udp: !include conx/sensors/udp.yaml


logger:
  default: info
  logs:
    homeassistant.components.cloud: debug

