# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

#config:
#frontend:
#image:
#person:
#map:
#history:
#logbook:
#sun:


# Example filter to include specified domains and exclude specified entities
recorder:
  include:
    domains:
      - sensor


# Text to speech
# Example configuration.yaml entry for Google Translate TTS service
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://127.0.0.1:8123
    service_name: google_say


group: !include groups.yaml
automation: !include_dir_list automation/
#automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

conx: !include conx/devices.yaml
switch automata: !include conx/switches/automata.yaml
light dmx: !include conx/lights/dmx.yaml
light kincoy: !include conx/lights/kincony.yaml
switch kincony: !include conx/switches/kincony.yaml
sensor automata: !include conx/sensors/automata.yaml
light moshiko_i_can_write_what_ever_i_like: !include conx/lights/automata.yaml

panel_custom:
  - name: conx-editor-panel
    url_path: conx-editor
    sidebar_title: Conx Editor
    sidebar_icon: mdi:server
    module_url: /local/conx/conx.js
    config:
      hello: world