# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

media_player:

discovery:

# Example filter to include specified domains and exclude specified entities
recorder:
  include:
    domains:
      - sensor


# Text to speech
# Example configuration.yaml entry for Google Translate TTS service
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://127.0.0.1:8123
    service_name: google_say

conx:
  dmx:
    - name: "dmx1"
      ip: "192.168.1.36"
      universe: 0
      channels: 32
      fps: 20

    - name: "dmx2"
      ip: "192.168.1.36"
      universe: 1
      channels: 32

  automata:
    - name: "autoBox1"
      ip: "192.168.1.36"
      port: 1001
      type: "input"

    - name: "autoBox2"
      ip: "192.168.1.36"
      port: 1002
      type: "output"

    - name: "autoBox3"
      ip: "192.168.1.36"
      port: 1003
      type: "panel"

  kincony:
    - name: "kinconyBox1"
      ip: "192.168.1.36"
      port: 4196
      type: "input"




group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
switch: !include switches.yaml

light:
  - platform: conx
    dmx:
      - dmxName: dmx1
        channel: 1
        name: conxDimmer1
        type: dimmer

      - dmxName: dmx1
        channel: 2
        name: conxDimmer2
        type: dimmer

      - dmxName: dmx1
        channel: 3
        name: conxDimmer3
        type: dimmer

      - dmxName: dmx1
        channel: 4
        name: conxDimmer4
        type: dimmer

      - dmxName: dmx1
        channel: 5
        name: conxDimmer5
        type: dimmer

      - dmxName: dmx1
        channel: 6
        name: conxDimmer6
        type: dimmer

      - dmxName: dmx1
        channel: 7
        name: conxDimmer7
        type: dimmer

      - dmxName: dmx1
        channel: 8
        name: conxDimmer8
        type: dimmer

      - dmxName: dmx1
        channel: 9
        name: conxDimmer9
        type: dimmer

      - dmxName: dmx1
        channel: 10
        name: conxColor
        type: rgb

      - dmxName: dmx2
        channel: 1
        name: conxDimmer22
        type: dimmer

      - dmxName: dmx2
        channel: 10
        name: conxColor2
        type: rgba

    automata:
      - boxName: autoBox2
        channel: 1
        name: conxAutoLight1

      - boxName: autoBox2
        channel: 2
        name: conxAutoLight2

      - boxName: autoBox2
        channel: 3
        name: conxAutoLight3

    kincony:
      - boxName: kinconyBox1
        channel: 1
        name: kinconyLight1

      - boxName: kinconyBox1
        channel: 2
        name: kinconyLight2

      - boxName: kinconyBox1
        channel: 3
        name: kinconyLight3


sensor:
  - platform: conx
    automata:
      - boxName: autoBox1
        channel: 1
        name: conxSensor1

      - boxName: autoBox1
        channel: 2
        name: conxSensor2

      - boxName: autoBox1
        channel: 3
        name: conxSensor3