# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

media_player:

discovery:

# Example filter to include specified domains and exclude specified entities
recorder:
  include:
    domains:
      - sensor


# Text to speech
# Example configuration.yaml entry for Google Translate TTS service
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: http://127.0.0.1:8123
    service_name: google_say


group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
scene: !include scenes.yaml

conx: !include conx.yaml


light: !include_dir_merge_list lights/
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensors/

