cues:
  x:
    light.rgb_1:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.0
        transition: 4.0
    light.rgb_2:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.3333333333333333
        transition: 4.0
    light.rgb_3:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.6666666666666666
        transition: 4.0
    light.rgb_4:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 1.0
        transition: 4.0
    light.rgb_5:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 100.0
        rgb_color:
        - 255
        - 0
        - 0
        transition: 4.0
    switch.sw1:
      state: 'off'
      atts:
        transition: 4.0
    switch.sw2:
      state: 'off'
      atts:
        transition: 4.0
    switch.sw3:
      state: 'off'
      atts:
        transition: 4.0
  y:
    light.rgb_1:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.0
        transition: 4.0
    switch.sw1:
      state: 'on'
      atts:
        transition: 4.0
    switch.sw2:
      state: 'on'
      atts:
        transition: 4.0
    switch.sw3:
      state: 'on'
      atts:
        transition: 4.0
sk:
  all:
    type: group
    idx: 12
    data: $rgb;1>10
  odds:
    type: group
    idx: 13
    data: $rgb;1>10|2
  isin:
    type: script
    idx: 8
    data:
      domain: conx
      service: light
      data:
        transition: 10
        intensity:
          fn: sin
          cycle: 4
      soft: true
  even:
    type: group
    idx: 10
    data: $rgb;2>10|2
  effs:
    type: folder
    idx: 0
    data: {}
  grs:
    type: folder
    idx: 1
    data:
      all:
        type: group
        idx: 13
        data: $rgb;1>10
      odds:
        type: group
        idx: 11
        data: $rgb;1>10|2
  rainbow:
    type: script
    idx: 20
    data:
      domain: conx
      service: light
      data:
        transition: 0
        hue:
          fn: up
          cycle: 4
          loop: 6
      soft: true
