cues:
  BO:
    light.dim_1:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_2:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_3:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_4:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_5:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_6:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_7:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_8:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_9:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.dim_10:
      state: 'off'
      atts:
        brightness: 0
        transition: 2
    light.rgb_1:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.0
        transition: 2
    light.rgb_2:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.3333333333333333
        transition: 2
    light.rgb_3:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 0.6666666666666666
        transition: 2
    light.rgb_4:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        hue:
          fn: sin
          offset: 1
          cycle: 2
          loop: 2
          index: 1.0
        transition: 2
    light.rgb_5:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 0.0
        - 100.0
        rgb_color:
        - 255
        - 0
        - 0
        transition: 2
    light.rgb_6:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 138.443
        - 95.686
        rgb_color:
        - 11
        - 255
        - 86
        transition: 2
    light.rgb_7:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 138.443
        - 95.686
        rgb_color:
        - 11
        - 255
        - 86
        transition: 2
    light.rgb_8:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 138.443
        - 95.686
        rgb_color:
        - 11
        - 255
        - 86
        transition: 2
    light.rgb_9:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 138.443
        - 95.686
        rgb_color:
        - 11
        - 255
        - 86
        transition: 2
    light.rgb_10:
      state: 'off'
      atts:
        brightness: 0
        hs_color:
        - 138.443
        - 95.686
        rgb_color:
        - 11
        - 255
        - 86
        transition: 2
  FL:
    light.dim_1:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_2:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_3:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_4:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_5:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_6:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_7:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_8:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_9:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.dim_10:
      state: 'on'
      atts:
        brightness: 255
        transition: 2
    light.rgb_1:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_2:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_3:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_4:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_5:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_6:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_7:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_8:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_9:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
    light.rgb_10:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 0.0
        - 0.0
        rgb_color:
        - 255
        - 255
        - 255
        transition: 2
  cue1:
    light.dim_1:
      state: 'on'
      atts:
        brightness: 190
        transition: 2
    light.dim_2:
      state: 'on'
      atts:
        brightness: 128
        transition: 2
    light.dim_3:
      state: 'on'
      atts:
        brightness: 190
        transition: 2
    light.dim_4:
      state: 'on'
      atts:
        brightness: 128
        transition: 2
    light.dim_5:
      state: 'on'
      atts:
        brightness: 190
        transition: 2
    light.dim_6:
      state: 'on'
      atts:
        brightness: 128
        transition: 2
    light.dim_7:
      state: 'on'
      atts:
        brightness: 190
        transition: 2
    light.dim_8:
      state: 'on'
      atts:
        brightness: 128
        transition: 2
    light.dim_9:
      state: 'on'
      atts:
        brightness: 190
        transition: 2
    light.dim_10:
      state: 'on'
      atts:
        brightness: 128
        transition: 2
  dcue1: {}
  cue2:
    light.rgb_1:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 3.294
        - 100.0
        rgb_color:
        - 255
        - 14
        - 0
        transition: 2
    light.rgb_2:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 120.0
        - 100.0
        rgb_color:
        - 0
        - 255
        - 0
        transition: 2
    light.rgb_3:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 3.294
        - 100.0
        rgb_color:
        - 255
        - 14
        - 0
        transition: 2
    light.rgb_4:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 120.0
        - 100.0
        rgb_color:
        - 0
        - 255
        - 0
        transition: 2
    light.rgb_5:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 3.294
        - 100.0
        rgb_color:
        - 255
        - 14
        - 0
        transition: 2
    light.rgb_6:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 120.0
        - 100.0
        rgb_color:
        - 0
        - 255
        - 0
        transition: 2
    light.rgb_7:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 3.294
        - 100.0
        rgb_color:
        - 255
        - 14
        - 0
        transition: 2
    light.rgb_8:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 120.0
        - 100.0
        rgb_color:
        - 0
        - 255
        - 0
        transition: 2
    light.rgb_9:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 3.294
        - 100.0
        rgb_color:
        - 255
        - 14
        - 0
        transition: 2
    light.rgb_10:
      state: 'on'
      atts:
        brightness: 255
        hs_color:
        - 120.0
        - 100.0
        rgb_color:
        - 0
        - 255
        - 0
        transition: 2
sk:
  all:
    type: group
    idx: 0
    data: $rgb;1>10
  odd:
    type: group
    idx: 1
    data: $rgb;1>10|2
  even:
    type: group
    idx: 2
    data: $rgb;2>10|2
  dall:
    type: group
    idx: 5
    data: $dim;1>10
  dodd:
    type: group
    idx: 6
    data: $dim;1>10|2
  deven:
    type: group
    idx: 7
    data: $dim;2>10|2
  total:
    type: group
    idx: 10
    data: $dim;1>10,$rgb;1>10
  BO:
    type: script
    idx: 4
    data:
      domain: conx
      service: cueplay
      data:
        name: BO
        soft: true
  FL:
    type: script
    idx: 9
    data:
      domain: conx
      service: cueplay
      data:
        name: FL
        soft: true
  rainbow:
    type: script
    idx: 18
    data:
      domain: conx
      service: light
      data:
        hue:
          fn: up
          offset: 1
          cycle: 4
          loop: 0
        soft: true
  sin:
    type: script
    idx: 19
    data:
      domain: conx
      service: light
      data:
        intensity:
          fn: sin
          offset: 1
          cycle: 4
          loop: 0
        soft: true
  alll:
    type: group
    idx: 14
    data: $dim;1>10,$rgb;1>10
  cue1:
    type: script
    idx: 20
    data:
      domain: conx
      service: cueplay
      data:
        name: cue1
        soft: true
  cue2:
    type: script
    idx: 21
    data:
      domain: conx
      service: cueplay
      data:
        name: cue2
        soft: true
  d1:
    type: folder
    idx: 16
    data:
      d2:
        type: folder
        idx: 12
        data: {}
  i was there before:
    type: folder
    idx: 13
    data: {}
