call_according_udp_sensor:
  alias: Call_according_udp_sensor
  sequence:
  - service: script.{{ states('sensor.udpSensor') }}
    data: {}
  mode: single
callscript:
  alias: CallScript
  sequence:
  - service: script.9cut
    data: {}
  mode: single
store:
  alias: Store
  sequence:
  - service: conx.cuestore
    data: {}
  mode: single
delete:
  alias: Delete
  sequence:
  - service: conx.cuedelete
    data: {}
  mode: single
play:
  alias: Play
  sequence:
  - service: conx.cueplay
    data: {}
  mode: single
