call_according_udp_sensor:
  alias: Call_according_udp_sensor
  sequence:
  - service: script.{{ states('sensor.udpSensor') }}
    data: {}
  mode: single
callscript:
  alias: CallScript
  sequence:
  - service: script.9cut
    data: {}
  mode: single
store:
  alias: Store
  sequence:
  - service: conx.cuestore
    data: {}
  mode: single
delete:
  alias: Delete
  sequence:
  - service: conx.cuedelete
    data: {}
  mode: single
play:
  alias: Play
  sequence:
  - service: conx.cueplay
    data: {}
  mode: single
selection:
  alias: Selection
  sequence:
  - service: conx.select
    data:
      id: '{{ states.input_text.selection.state }}

        '
  mode: single
name:
  alias: Name
  sequence:
  - service: conx.name
    data:
      name: '{{ states.input_text.name.state }}

        '
  mode: single
transition:
  alias: Transition
  sequence:
  - service: conx.transition
    data:
      value: '{{ states.input_number.transition.state }}

        '
  mode: single
