- platform: conx
  automata:
    - boxName: autoBox3
      channel: 1
      name: conxSwitchlala1

    - boxName: autoBox3
      channel: 2
      name: conxSwitch2

    - boxName: autoBox3
      channel: 3
      name: conxSwitch3

