- platform: conx
  automata:
    - boxName: autoBox3
      channel: 1
      name: sw1

    - boxName: autoBox3
      channel: 2
      name: sw2

    - boxName: autoBox3
      channel: 3
      name: sw3

