- platform: conx
  kincony:
    - boxName: kinconyBox1
      channel: 4
      name: kinconySwitch4

    - boxName: kinconyBox1
      channel: 5
      name: kinconySwitch5

    - boxName: kinconyBox1
      channel: 6
      name: kinconySwitch6
